autoload -U compinit; compinit

[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)
command -v starship &> /dev/null && eval   "$(starship init zsh)"
command -v kubectl  &> /dev/null && source <(kubectl completion zsh)
command -v spin     &> /dev/null && source <(spin completion)
[[ -f /opt/dev/dev.sh ]] && source /opt/dev/dev.sh
[[ -x /opt/dev/sh/chruby/chruby.sh ]] && type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; }
[[ -d ~/.kube ]] && for file in ~/.kube/*; do [[ $file = ~/.kube/config* ]] && export KUBECONFIG="${KUBECONFIG}:${file}"; done
[[ -f ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]] && source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
[[ -f ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export EDITOR="code -w"

###
## Aliases
###
command -v kubectl    &> /dev/null && alias k=kubectl
command -v kubens     &> /dev/null && alias kn=kubens
command -v kubectx    &> /dev/null && alias kc=kubectx
command -v systemctl  &> /dev/null && alias sc=systemctl
command -v journalctl &> /dev/null && alias jc=journalctl
command -v bat        &> /dev/null && alias cat=bat
command -v batcat     &> /dev/null && alias cat=batcat

if [[ -d ~/.config/spin ]]; then
    command -v kubectl &> /dev/null && alias kprod='kubectl --context "$(cat ~/.config/spin/spin.up.dev/cluster)" -n "$(cat ~/.config/spin/spin.up.dev/namespace)"'
    command -v kubectl &> /dev/null && alias kdev='kubectl --context "$(cat ~/.config/spin/localhost/cluster)" -n "$(cat ~/.config/spin/localhost/namespace)"'
fi

###
## SHOPIFY
###
[[ -d ~/src/github.com/Shopify/cloudplatform/workflow-utils ]] && for file in ~/src/github.com/Shopify/cloudplatform/workflow-utils/*.bash; do source ${file}; done

if [ $SPIN ]; then
    export SPIN_HISTFILE="~/.config/spin/config/zsh_history"
    [[ -f /etc/zsh/zshrc.default.inc.zsh ]] && source /etc/zsh/zshrc.default.inc.zsh
fi

[[ -f /opt/dev/sh/chruby/chruby.sh ]] && type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; }

# cloudplatform: add Shopify clusters to your local kubernetes config
export KUBECONFIG=${KUBECONFIG:+$KUBECONFIG:}/Users/joshbaker/.kube/config:/Users/joshbaker/.kube/config.shopify.cloudplatform
