#!/usr/bin/env bash

NC='\033[0m'
BCyan='\033[1;36m'
BGreen='\033[1;32m'       # Green
BBlue='\033[1;34m'        # Blue

echo -e "${BCyan}[Installing packages${NC}]"
case $( uname -s ) in
Linux) /bin/sh setup_linux;;
Darwin) /bin/sh setup_mac;;
*)     echo other;;
esac

git submodule init; git submodule update

echo -e "${BGreen}[Installing dotfiles]${NC}"
DOTFILES_DIR=~/src/github.com/joshlbaker/dotfiles
if [ "$SPIN" ]; then
    DOTFILES_DIR=~/dotfiles
fi
for i in "$DOTFILES_DIR"/dotfiles/*; do
  echo -e ".$(basename "$i")"
  [ -d ~/."$(basename "$i")" ] && rm -rf ~/."$(basename "$i")"
  ln -sf "$i" ~/."$(basename "$i")"
done

echo -e "${BBlue}[Adding configs]${NC}"
mkdir -p ~/.config
for i in "$DOTFILES_DIR"/config/*; do
  echo -e "$(basename "$i")"
  [ -d ~/.config/"$(basename "$i")" ] && rm -rf ~/.config/"$(basename "$i")"
  ln -sf "$i" ~/.config/"$(basename "$i")"
done
